---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: ID
  description: Product ID
- name: name
  type: text
  config:
    required: false
  label: Name
  description: Product Name
- name: price_in_r
  type: number
  label: Price in R
  description: Price for the product
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
  description: Product Description
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
